source 'https://rubygems.org'

ruby '>= 3.2'

# Pin temporalio from the local feat/tool-registry branch.
# Once the SDK publishes, swap to: gem 'temporalio', '>= X.Y.Z'
gem 'temporalio', path: '/Users/alex/checkouts/temporal/sdk-ruby/temporalio'
gem 'anthropic', '>= 1.0.0'

group :test do
  gem 'minitest', '~> 5.20'
end
